---

- name: Create Azure private output directory
  ansible.builtin.file:
    path: "{{ tf_config_dir }}/azure-private"
    state: directory
    mode: '0700'

- name: Deploy Azure private variables source templates
  ansible.builtin.template:
    src: "azure/variables.source.j2"
    dest: "{{ tf_config_dir }}/azure-private/variables.source"
    mode: '0600'

- name: Generate ssh RSA public/private key
  ansible.builtin.command:
    cmd: ssh-keygen -t rsa -N '' -f azure_id_rsa
    chdir: "{{ tf_config_dir }}/azure-private"
    creates: azure_id_rsa.pub
  when:
    - not azure_vm_admin_ssh_public_key_file is defined
    - azure_vm_disable_password_authentication | bool

- name: Set the ssh RSA public key fact
  ansible.builtin.set_fact:
    azure_vm_admin_ssh_public_key_file: "{{ tf_config_dir }}/azure-private/azure_id_rsa.pub"
  when:
    - not azure_vm_admin_ssh_public_key_file is defined

- name: Storage container azure-init definition
  block:
    - name: Purge azure-init output directory
      ansible.builtin.file:
        path: "{{ tf_config_dir }}/azure-init"
        state: absent
      when:
        - tf_purge | bool

    - name: Create azure-init output directory
      ansible.builtin.file:
        path: "{{ tf_config_dir }}/azure-init"
        state: directory
        mode: '0750'

    - name: Deploy resources templates
      ansible.builtin.template:
        src: "azure/{{ item }}.tf.j2"
        dest: "{{ tf_config_dir }}/azure-init/{{ item }}.tf"
        mode: '0640'
      with_items:
        - "{{ azure_tfstate_resources }}"
      vars:
        skip_azure_backend: true
        azure_resource_group_name: "{{ azure_tfstate_resource_group_name }}"
        azure_storage_account_name: "{{ tf_tfstate_on_azure_storage_container }}"
        azure_storage_container_name: "{{ tf_tfstate_on_azure_storage_container }}"
  when:
    - tf_tfstate_on_azure_storage_container is defined

- name: Purge azure output directory
  ansible.builtin.file:
    path: "{{ tf_config_dir }}/azure"
    state: absent
  when:
    - tf_purge | bool

- name: Create Azure output directory
  ansible.builtin.file:
    path: "{{ tf_config_dir }}/azure"
    state: directory
    mode: '0750'

- name: Deploy Azure general resources templates
  ansible.builtin.template:
    src: "azure/{{ item }}.tf.j2"
    dest: "{{ tf_config_dir }}/azure/{{ item }}.tf"
    mode: '0640'
  with_items:
    - "{{ azure_resources }}"

- name: Deploy Azure VPN resources templates
  ansible.builtin.template:
    src: "azure/{{ item }}.tf.j2"
    dest: "{{ tf_config_dir }}/azure/{{ item }}.tf"
    mode: '0640'
  with_items:
    - "{{ azure_vpn_resources }}"

- name: Deploy Azure key vault template
  ansible.builtin.template:
    src: "azure/key_vault.tf.j2"
    dest: "{{ tf_config_dir }}/azure/key_vault.tf"
    mode: '0640'
  when:
    - azure_key_vault_enable | bool

- name: Deploy Azure database template
  ansible.builtin.template:
    src: "azure/database.tf.j2"
    dest: "{{ tf_config_dir }}/azure/database.tf"
    mode: '0640'
  when:
    - azure_database_servers is defined

- name: Deploy Azure virtual machines specific templates
  ansible.builtin.include_tasks: azure-vms.yml
  with_items:
    - "{{ azure_vms_groups }}"
  loop_control:
    loop_var: group_name

- name: Cleanup Azure manifests
  ansible.builtin.include_tasks: azure-cleanup.yml

- name: Display a reminder for sourcing variables
  ansible.builtin.debug:
    msg:
      - "Remember to import the variable file in order to tell the tf cmd which"
      - "subscription use during the run. Before run the tf cmd, please execute:"
      - "    source {{ tf_config_dir }}/azure-private/variables.source"
