---

- name: Purge Libvirt output directory
  ansible.builtin.file:
    path: "{{ tf_config_dir }}"
    state: absent
  when:
    - tf_purge | bool

- name: Create Libvirt output directory
  ansible.builtin.file:
    path: "{{ tf_config_dir }}"
    state: directory
    mode: '0750'

- name: Create Libvirt private output directory
  ansible.builtin.file:
    path: "{{ tf_config_dir }}/private"
    state: directory
    mode: '0700'

- name: Deploy Libvirt private variables source templates
  ansible.builtin.template:
    src: "libvirt/variables.source.j2"
    dest: "{{ tf_config_dir }}/private/variables.source"
    mode: '0600'

- name: Deploy Libvirt general resources templates
  ansible.builtin.template:
    src: "libvirt/{{ item }}.tf.j2"
    dest: "{{ tf_config_dir }}/{{ item }}.tf"
    mode: '0640'
  with_items:
    - 'provider'
    - 'networks'
    - 'pools'
    - 'volumes'
    - 'cloud_init'
    - 'coreos_ignition'

# Deploy the cloud_init.cfg, for details look at:
# https://cloudinit.readthedocs.io/en/latest/reference/examples.html
- name: Deploy Libvirt cloud_init.cfg file
  ansible.builtin.copy:
    content: |
      #cloud-config
      {{ item.cfg | to_nice_yaml(indent=2, width=9999) }}
    dest: "{{ tf_config_dir }}/cloud_init_{{ item.name }}.cfg"
    mode: '0640'
  with_items:
    - "{{ tf_libvirt_cloud_inits }}"

- name: Deploy Libvirt virtual machines specific templates
  ansible.builtin.include_tasks: libvirt-vms.yml
  with_items:
    - "{{ tf_libvirt_vms_groups }}"
  loop_control:
    loop_var: tf_group_name

- name: Cleanup Libvirt manifests and configurations
  ansible.builtin.include_tasks: libvirt-cleanup.yml

- name: Display a reminder for sourcing variables
  ansible.builtin.debug:
    msg:
      - "Remember to import the variable file in order to tell the tf cmd which"
      - "subscription use during the run. Before run the tf cmd, please execute:"
      - "    source {{ tf_config_dir }}/private/variables.source"
